version: '3.8'
services:

  # PHP Service
  app:
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    container_name: blog-app
    restart: unless-stopped
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
    depends_on:
      - database
      - redis
    networks:
      - blog
      
  # Database Server
  database:
    image: mysql:latest
    container_name: blog-db
    restart: always
    ports:
      - 3306:3306
    command: mysqld --default-authentication-plugin=caching_sha2_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - blog
    
  # Redis Server
  redis:
    image: redis:alpine
    container_name: blog-redis
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - 6379:6379
    networks:
      - blog

volumes:
  db-data: ~

networks:
  blog:
    driver: bridge